name: Coverage

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      coverage:
        description: 'Run coverage'
        required: true
        default: 'true' # or false

jobs:
  coverage-report:
    name: Coverage report
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/') || github.event.inputs.coverage == 'true' || github.event_name == 'push'
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.3.1']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.2.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          poetry install --sync --all-extras --with dev,coverage,test
      - name: Run tests and collect coverage
        run: |
          poetry run pytest --cov=./src --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
